"use client";
import { FormEvent, useState } from "react";
import { CheckCircle2, PlugZap } from "lucide-react";
import { DemoBadge } from "@/components/ui/DemoBadge";
import { nextDemoId } from "@/lib/utils";
import { useLanguage } from "@/hooks/useLanguage";

export function InstallationPanel() {
  const { t } = useLanguage();
  const [id,setId] = useState<string | null>(null);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setId(nextDemoId("IN")); event.currentTarget.reset(); }
  return <div className="space-y-8"><div><DemoBadge compact/><h1 className="dashboard-title mt-4">{t("installation.title")}</h1><p className="dashboard-subtitle">{t("installation.subtitle")}</p></div><div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><form onSubmit={submit} className="surface-card p-5 sm:p-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold text-brand-950/60">{t("installation.serviceType")}<select className="form-field mt-2" required><option value="Electricity">{t("requests.electricity")}</option><option value="Water">{t("requests.waterService")}</option><option value="Connectivity">{t("installation.connectivity")}</option></select></label><label className="text-xs font-semibold text-brand-950/60">{t("installation.customerName")}<input className="form-field mt-2" required/></label><label className="sm:col-span-2 text-xs font-semibold text-brand-950/60">{t("installation.address")}<input className="form-field mt-2" required placeholder="Demo service area"/></label><label className="text-xs font-semibold text-brand-950/60">{t("installation.phone")}<input className="form-field mt-2" required/></label><label className="text-xs font-semibold text-brand-950/60">{t("installation.email")}<input type="email" className="form-field mt-2" required/></label><label className="text-xs font-semibold text-brand-950/60">{t("installation.requestedDate")}<input type="date" className="form-field mt-2" required/></label><label className="sm:col-span-2 text-xs font-semibold text-brand-950/60">{t("installation.notes")}<textarea className="form-field mt-2 resize-none" rows={4}/></label></div><button className="button-primary mt-5" type="submit"><PlugZap className="h-4 w-4"/>{t("installation.submit")}</button></form><div className="surface-card grid min-h-80 place-items-center p-6 text-center">{id?<div><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600"/><p className="mt-4 text-xs font-bold uppercase tracking-[.15em] text-brand-500">{t("installation.confirmation")}</p><h2 className="mt-2 font-mono text-2xl font-semibold">{id}</h2><p className="mt-3 text-sm text-brand-950/50">{t("common.status")}: {t("installation.received")}</p></div>:<p className="max-w-sm text-sm leading-6 text-brand-950/45">{t("common.demoOnly")}</p>}</div></div></div>;
}
