"use client";
import { useState } from "react";
import { CheckCircle2, Clock3, MapPin, Navigation, Play, TriangleAlert, Truck, UsersRound, Wrench } from "lucide-react";
import { DemoBadge } from "@/components/ui/DemoBadge";
import { KpiCard } from "@/components/ui/KpiCard";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { useApp } from "@/components/motion/AppProviders";
import type { Technician, TechnicianStatus } from "@/lib/types";

const statusCycle: TechnicianStatus[]=["Available","En Route","On Site","Offline"];
export function FieldServicePanel(){const {t,technicians,setTechnicians}=useApp();const [jobStage,setJobStage]=useState(0);const available=technicians.filter(x=>x.status==="Available").length;function cycle(tech:Technician){const index=statusCycle.indexOf(tech.status);const status=statusCycle[(index+1)%statusCycle.length];setTechnicians(current=>current.map(item=>item.id===tech.id?{...item,status}:item));}
const steps=[[t("field.startJob"),Play],[t("field.arrived"),MapPin],[t("field.beginWork"),Wrench],[t("field.completeJob"),CheckCircle2]] as const;
return <div className="space-y-8"><div><DemoBadge compact/><h1 className="dashboard-title mt-4">{t("field.title")}</h1><p className="dashboard-subtitle">{t("field.subtitle")}</p></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label={t("platform.activeTechnicians")} value={String(technicians.filter(x=>x.status!=="Offline").length)} icon={UsersRound}/><KpiCard label={t("platform.scheduledJobs")} value="8" icon={Clock3}/><KpiCard label={t("platform.urgentJobs")} value="2" icon={TriangleAlert}/><KpiCard label={t("field.available")} value={String(available)} icon={Truck}/></section>
<section className="grid gap-5 2xl:grid-cols-[1.25fr_.75fr]"><div className="surface-card p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-semibold">{t("field.available")}</h2><span className="text-xs text-brand-950/35">{t("common.demoData")}</span></div><div className="table-shell"><table className="table-base"><thead><tr><th>{t("maintenance.technician")}</th><th>{t("field.specialization")}</th><th>{t("common.status")}</th><th>{t("field.currentTask")}</th><th>{t("field.location")}</th><th>{t("field.eta")}</th><th/></tr></thead><tbody>{technicians.map(tech=><tr key={tech.id}><td className="font-semibold">{tech.name}</td><td>{tech.specialization}</td><td><StatusBadge tone={tech.status==="Available"?"good":tech.status==="Offline"?"neutral":"attention"}>{t(`status.${tech.status.replaceAll(" ", "")}`)}</StatusBadge></td><td>{tech.currentTask}</td><td>{tech.location}</td><td>{tech.eta}</td><td><button onClick={()=>cycle(tech)} className="text-xs font-semibold text-brand-500">{t("common.update")}</button></td></tr>)}</tbody></table></div></div>
<div className="surface-card overflow-hidden"><div className="border-b border-brand-950/[.07] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-brand-500">{t("field.todayJobs")}</p><h2 className="mt-2 text-xl font-semibold">SR-2026-00128</h2></div><div className="p-5"><div className="space-y-4 text-sm"><div className="flex justify-between"><span className="text-brand-950/40">{t("field.jobLocation")}</span><span className="font-semibold">Demo Zone A</span></div><div className="flex justify-between"><span className="text-brand-950/40">{t("common.customer")}</span><span className="font-semibold">Demo Customer</span></div><div className="flex justify-between"><span className="text-brand-950/40">{t("common.priority")}</span><span className="font-semibold text-brand-500">High</span></div><div className="flex justify-between"><span className="text-brand-950/40">{t("field.parts")}</span><span className="font-semibold">Demo kit A</span></div><div className="flex justify-between"><span className="text-brand-950/40">{t("field.estimatedTime")}</span><span className="font-semibold">45 min</span></div></div><div className="mt-6 grid gap-2">{steps.map(([label,Icon],index)=><button key={label} onClick={()=>setJobStage(Math.max(jobStage,index+1))} className={`flex items-center gap-3 rounded-xl border p-3 text-left text-xs font-semibold transition ${index<jobStage?"border-emerald-500/20 bg-emerald-500/5 text-emerald-700":"border-brand-950/[.08] hover:border-brand-500/25"}`}><span className={`grid h-8 w-8 place-items-center rounded-lg ${index<jobStage?"bg-emerald-500 text-white":"bg-brand-mist text-brand-500"}`}><Icon className="h-4 w-4"/></span>{label}</button>)}</div><button className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-red-500/15 p-3 text-xs font-semibold text-red-600"><TriangleAlert className="h-4 w-4"/>{t("field.reportIssue")}</button></div></div></section>
<section className="surface-card overflow-hidden"><div className="flex flex-col gap-2 border-b border-brand-950/[.07] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold">{t("field.serviceMap")}</h2><p className="mt-1 text-xs text-brand-950/40">{t("field.mapNote")}</p></div><span className="rounded-full bg-brand-500/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-brand-500">{t("common.simulated")}</span></div><div className="network-grid relative h-[380px] overflow-hidden bg-[#f7efea] sm:h-[460px]"><svg className="absolute inset-0 h-full w-full" viewBox="0 0 900 460" aria-label={t("field.serviceMap")}><path d="M30 350C150 280 230 380 350 260S570 100 850 180" fill="none" stroke="#FF7700" strokeWidth="7" strokeLinecap="round" opacity=".65"/><path d="M60 110C200 180 250 95 390 150s250 180 460 120" fill="none" stroke="#A05937" strokeWidth="5" strokeDasharray="8 14" opacity=".45"/>{[[120,300],[260,330],[390,240],[540,160],[700,155],[790,250]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="22" fill="#32201F" opacity=".92"/><circle cx={x} cy={y} r="7" fill="#FF963E"/></g>)}{[[190,120],[490,320],[650,245]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="17" fill="#FF7700"/><path d={`M${x-5} ${y}h10M${x} ${y-5}v10`} stroke="#fff" strokeWidth="3"/></g>)}</svg><div className="absolute bottom-5 left-5 rounded-2xl border border-white/70 bg-white/90 p-4 text-xs shadow-xl backdrop-blur"><div className="flex items-center gap-2"><Navigation className="h-4 w-4 text-brand-500"/>Demo technician markers</div><div className="mt-2 flex items-center gap-2"><span className="h-3 w-3 rounded-full bg-brand-500"/>Demo service request</div></div></div></section></div>}
